spring:
  application:
    name: Nostra Movie
  datasource:
    url: jdbc:postgresql://localhost:5432/nostramovie
    username: Nostra
    password: root

server:
  port: 8282
  servlet:
    context-path: /mockup
